export const CHANGE_SORT_TYPE = 'CHANGE_SORT_TYPE';
export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE';
export const GET_MOVIES = 'GET_MOVIES';
export const CHANGE_CURRENT_MOVIE = 'CHANGE_CURRENT_MOVIE';
