// APP
export const CHANGE_SORT_TYPE = 'CHANGE_SORT_TYPE';
export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE';
export const CHANGE_CURRENT_MOVIE = 'CHANGE_CURRENT_MOVIE';

//DATA-SERVICE
export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
export const CHANGE_SEARCH_QUERY = 'CHANGE_SEARCH_QUERY';
